name: second
on: push
jobs:
  job-1:
    name: nothing
    runs-on: ubuntu-latest
    steps:
      - run: echo "user"
      - run: free -m
  job-2:
    needs: job-1
    name: nothing2
    runs-on: ubuntu-latest
    steps:
      - run: echo "2"
      - run: date
  job-3:
    name: nothing3
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "3"
         hostname
        
        
        
